In [1]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.simplefilter('ignore')
plt.style.use('dark_background')
from sklearn.metrics import mean_squared_error as mse

In [2]:
data = pd.read_csv('transformed_housing_data2')
data

,Sale_Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),...,Ever_Renovated_Yes,Zipcode_Group_Zipcode_Group_1,Zipcode_Group_Zipcode_Group_2,Zipcode_Group_Zipcode_Group_3,Zipcode_Group_Zipcode_Group_4,Zipcode_Group_Zipcode_Group_5,Zipcode_Group_Zipcode_Group_6,Zipcode_Group_Zipcode_Group_7,Zipcode_Group_Zipcode_Group_8,Zipcode_Group_Zipcode_Group_9
0,221900.0,3,1.00,1180.0,5650.0,1.0,0,7,1180.0,0,...,0,0,0,0,0,0,0,0,0,0
1,538000.0,3,2.25,2570.0,7242.0,2.0,0,7,2170.0,400,...,1,0,1,0,0,0,0,0,0,0
2,180000.0,2,1.00,770.0,10000.0,1.0,0,6,770.0,0,...,0,0,1,0,0,0,0,0,0,0
3,604000.0,4,3.00,1960.0,5000.0,1.0,0,7,1050.0,910,...,0,0,0,1,0,0,0,0,0,0
4,510000.0,3,2.00,1680.0,8080.0,1.0,0,8,1680.0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21604,360000.0,3,2.50,1530.0,1131.0,3.0,0,8,1530.0,0,...,0,0,0,1,0,0,0,0,0,0
21605,400000.0,4,2.50,2310.0,5813.0,2.0,0,8,2310.0,0,...,0,1,0,0,0,0,0,0,0,0
21606,402101.0,2,0.75,1020.0,1350.0,2.0,0,7,1020.0,0,...,0,0,0,1,0,0,0,0,0,0
21607,400000.0,3,2.50,1600.0,2388.0,2.0,0,8,1600.0,0,...,0,0,0,0,1,0,0,0,0,0
21608,325000.0,2,0.75,1020.0,1076.0,2.0,0,7,1020.0,0,...,0,0,0,1,0,0,0,0,0,0

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Y = data['Sale_Price']
X = scaler.fit_transform(data.drop(columns = ['Sale_Price']))
X = pd.DataFrame(data = X, columns = data.drop(columns = ['Sale_Price']).columns)
X.head()

,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),...,Ever_Renovated_Yes,Zipcode_Group_Zipcode_Group_1,Zipcode_Group_Zipcode_Group_2,Zipcode_Group_Zipcode_Group_3,Zipcode_Group_Zipcode_Group_4,Zipcode_Group_Zipcode_Group_5,Zipcode_Group_Zipcode_Group_6,Zipcode_Group_Zipcode_Group_7,Zipcode_Group_Zipcode_Group_8,Zipcode_Group_Zipcode_Group_9
0,-0.398724,-1.447526,-0.979905,-0.228291,-0.915389,-0.30579,-0.563993,-0.734722,-0.658697,0.544734,...,-0.210155,-0.350481,-0.482158,-0.419600,-0.479094,-0.214086,-0.287712,-0.112274,-0.16885,-0.048158
1,-0.398724,0.175684,0.533718,-0.189858,0.936817,-0.30579,-0.563993,0.460990,0.245134,0.680915,...,4.758385,-0.350481,2.074011,-0.419600,-0.479094,-0.214086,-0.287712,-0.112274,-0.16885,-0.048158
2,-1.474115,-1.447526,-1.426369,-0.123276,-0.915389,-0.30579,-1.468566,-1.229916,-0.658697,1.293731,...,-0.210155,-0.350481,2.074011,-0.419600,-0.479094,-0.214086,-0.287712,-0.112274,-0.16885,-0.048158
3,0.676667,1.149611,-0.130534,-0.243983,-0.915389,-0.30579,-0.563993,-0.891735,1.397518,0.204281,...,-0.210155,-0.350481,-0.482158,2.383223,-0.479094,-0.214086,-0.287712,-0.112274,-0.16885,-0.048158
4,-0.398724,-0.148958,-0.435436,-0.169628,-0.915389,-0.30579,0.340581,-0.130827,-0.658697,-0.544715,...,-0.210155,-0.350481,-0.482158,-0.419600,2.087275,-0.214086,-0.287712,-0.112274,-0.16885,-0.048158

In [4]:
from sklearn.model_selection import train_test_split as tts
x_train, x_test, y_train, y_test = tts(X, Y, test_size = 0.3, random_state = 101)

x_test.shape, x_train.shape, y_test.shape, y_train.shape

((6483, 30), (15126, 30), (6483,), (15126,))

In [5]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression(normalize = True)
lr.fit(x_train, y_train)

LinearRegression(normalize=True)

In [6]:
predictions = lr.predict(x_test)
lr.score(x_test, y_test)

0.8462355542468781

In [7]:
def adj_R2(data_x, data_y, predictions):
    from sklearn.metrics import r2_score
    R = r2_score(data_y, predictions)
    k = len(data_x.columns)
    n = len(data_y)
    adj_R = 1 - ((n -1)/(n - k - 1)) * (1 - R)
    return adj_R

In [8]:
r2 = adj_R2(x_test, y_test, predictions)
r2

0.8455205924718325

# Feature Selection

In [9]:
def adj_r2(m, data_y, predictions):
    from sklearn.metrics import r2_score
    R = r2_score(data_y, predictions)
    n = len(data_y)
    adj_R = 1 - ((n -1)/(n - m - 1)) * (1 - R)
    return adj_R

In [10]:
def return_r2(X, Y, model):
    '''
    X = independent variable
    Y = Independent variable / target
    model = predictive model
    
    returns the adjusted R2
    '''
    model.fit(X, Y)
    pred = model.predict(X)
    m = len(X.columns)
    return adj_r2(m, Y, pred)

In [11]:
def forward_selection(model, X, Y, max_features):
    '''
    X = independent variable
    Y = Independent variable / target
    model = predictive model
    max_features = selects best features upto max features value
    
    returns
    Rmax = adjusted r2 of the final model
    history = list of Rmax for every independent variable added to the variable
    X[f_col] = best features upto max features
    '''
    f_col = []
    history = []
    flag = 0
    elim = 0
    for i in range(max_features):
        f_col.append('blank')
        #print(f_col)
        tmp = f_col[:]
        Rmax = -1
        for var in X.columns:
            if var not in tmp:
                tmp[-1] = var
                r2 = return_r2(X[tmp], Y, model)
                flag += 1
                #print(tmp)
                if r2 >= Rmax:
                    f_col[-1] = var
                    Rmax = r2
                    elim = var
            #X.drop(columns = [elim], inplace = True)
        print('Selected', f_col[-1], 'with new R2', Rmax,'---',flag)
        history.append(Rmax)
    return Rmax, history, X[f_col]

In [12]:
# from sklearn.linear_model import LinearRegression
# lr = LinearRegression(normalize = True)

# score, history, sel_data = forward_selection(lr, x_train, y_train, 30)

In [15]:
import time
from sklearn.linear_model import LinearRegression
lr = LinearRegression(normalize = True)

# calculating time taken
tick = time.time()
score, history, sel_data = forward_selection(lr, x_train, y_train, 30)
tock = time.time()

Selected Flat Area (in Sqft) with new R2 0.4825106645259518 --- 30
Selected Latitude with new R2 0.6158682713046579 --- 59
Selected Overall Grade with new R2 0.6693250844517911 --- 87
Selected Age of House (in Years) with new R2 0.7101671809322652 --- 114
Selected Zipcode_Group_Zipcode_Group_8 with new R2 0.735965980189696 --- 140
Selected Zipcode_Group_Zipcode_Group_6 with new R2 0.7513359472574557 --- 165
Selected No of Times Visited with new R2 0.7665054219574295 --- 189
Selected Zipcode_Group_Zipcode_Group_4 with new R2 0.7765839357842504 --- 212
Selected Zipcode_Group_Zipcode_Group_7 with new R2 0.7867385851118124 --- 234
Selected Zipcode_Group_Zipcode_Group_3 with new R2 0.7966330954041451 --- 255
Selected Zipcode_Group_Zipcode_Group_5 with new R2 0.8135013723628121 --- 275
Selected Zipcode_Group_Zipcode_Group_9 with new R2 0.8192910381878412 --- 294
Selected Zipcode_Group_Zipcode_Group_2 with new R2 0.8242921707826699 --- 312
Selected Longitude with new R2 0.8266049066242157 --- 329
Selected Basement Area (in Sqft) with new R2 0.8295620645811876 --- 345
Selected Condition_of_the_House_Excellent with new R2 0.8318506623682476 --- 360
Selected Lot Area (in Sqft) with new R2 0.8339600690154836 --- 374
Selected Zipcode_Group_Zipcode_Group_1 with new R2 0.8356698063157928 --- 387
Selected Waterfront_View_Yes with new R2 0.837125308901623 --- 399
Selected Living Area after Renovation (in Sqft) with new R2 0.8384257980145959 --- 410
Selected No of Bathrooms with new R2 0.8394089149738739 --- 420
Selected Ever_Renovated_Yes with new R2 0.8399491254999183 --- 429
Selected Year since Renovation with new R2 0.8404605503169833 --- 437
Selected Condition_of_the_House_Good with new R2 0.8407704362899258 --- 444
Selected Condition_of_the_House_Fair with new R2 0.8409159992800564 --- 450
Selected No of Bedrooms with new R2 0.8410610037918913 --- 455
Selected Lot Area after Renovation (in Sqft) with new R2 0.8411171250786783 --- 459
Selected No of Floors with new R2 0.8411623663620638 --- 462
Selected Condition_of_the_House_Okay with new R2 0.8411797446658431 --- 464
Selected Area of the House from Basement (in Sqft) with new R2 0.8411713183817104 --- 465

In [16]:
print('time take to complete forward selection with bug:', tock-tick)

time take to complete forward selection with bug: 3.9999749660491943